# Some of Bioconda's supported versions are described
# in ../docs/source/user/versions.rst
# so please keep that documentation up to date as they change

# Additional bioconda-specific pinnings to use in addition to those specified
# in
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

# clear hard-coded default value for CONDA_BUILD_SYSROOT
CONDA_BUILD_SYSROOT:
  - ''

pin_run_as_build:
  htslib:
    max_pin: x.x
  bamtools:
    max_pin: x.x.x
  r-base:
    max_pin: x.x
    min_pin: x.x

htslib:
  - 1.12
libdeflate:
  - 1.7
bamtools:
  - 2.5.1

# NOTE: Workaround https://github.com/conda/conda-build/issues/3974 we slightly alter the values
#       from conda-forge-pinnings here (inserting '.*' or ' ' which should be ignored later on).
r_base:
  - 3.6.*
  - 4.0.*

python:
  - 3.9.*  *_cpython
  - 3.8.*  *_cpython
  - 3.7.*  *_cpython
  - 3.6.*  *_cpython
  - 2.7.*  *_cpython
# conda-forge only has 3 python versions, so we need to modify the length of the other zip_keys in its group
python_impl:
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
numpy:
  - 1.19.*
  - 1.17.*
  - 1.17.*
  - 1.17.*
  - 1.16.*

channel_sources:
  - hcc,conda-forge,bioconda,defaults

channel_targets:
  - hcc main

# HCC specific packages
cuda_driver:
  - 460.67      # [linux]
cuda_compiler_version:
  - 11.2                       # [linux64]
cudnn:
  - 8
cudatoolkit:
  - 11.2
mro:
  - 3.5

zip_keys:
- - cuda_compiler_version
  - cudnn

pin_run_as_build:
  mro:
    min_pin: x.x.x
    max_pin: x.x
  cuda_driver:          # [linux]
    max_pin: x.x        # [linux]
  cudatoolkit:          # [linux]
    max_pin: x.x        # [linux]
  cudnn:                # [linux]
    max_pin: x.x.x      # [linux]
