# Additional bioconda-specific pinnings to use in addition to those specified
# in
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

pin_run_as_build:
  htslib:
    max_pin: x.x
  bamtools:
    max_pin: x.x.x
  libdeflate:
    max_pin: x.x
  cuda_driver:          # [linux]
    max_pin: x.x        # [linux]
  cudatoolkit:          # [linux]
    max_pin: x.x        # [linux]
  cudnn:                # [linux]
    max_pin: x.x.x      # [linux]

htslib:
  - 1.9
bamtools:
  - 2.4.1
libdeflate:
  - 1.0
cuda_driver:    # [linux]
  - 410.73      # [linux]
cudatoolkit:    # [linux]
  - 9.2         # [linux]
cudnn:          # [linux]
  - 7.2.1       # [linux]
