# Additional bioconda-specific pinnings to use in addition to those specified
# in
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

# clear hard-coded default value for CONDA_BUILD_SYSROOT
CONDA_BUILD_SYSROOT:
  - ''

pin_run_as_build:
  htslib:
    max_pin: x.x
  bamtools:
    max_pin: x.x.x
  r-base:
    max_pin: x.x
    min_pin: x.x

htslib:
  - 1.9
bamtools:
  - 2.5.1
r_base:
  - 3.6


# HCC specific packages
cuda_driver:    # [linux]
  - 410.73      # [linux]
cudatoolkit:    # [linux]
  - 10.0        # [linux]
cudnn:          # [linux]
  - 7.6.5       # [linux]
mro:
  - 3.5

pin_run_as_build:
  mro:
    min_pin: x.x.x
    max_pin: x.x
  cuda_driver:          # [linux]
    max_pin: x.x        # [linux]
  cudatoolkit:          # [linux]
    max_pin: x.x        # [linux]
  cudnn:                # [linux]
    max_pin: x.x.x      # [linux]
