# Additional bioconda-specific pinnings to use in addition to those specified
# in
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

pin_run_as_build:
  htslib:
    max_pin: x.x
  bamtools:
    max_pin: x.x.x
  cuda-driver:
    max_pin: x.x
  cudatoolkit:
    max_pin: x.x
  cudnn:
    max_pin: x.x.x

htslib:
  - 1.7
bamtools:
  - 2.4.1
cuda-driver:
  - 375.66
cudatoolkit:
  - 8.0
cudnn:
  - 7.0.5
